#!/usr/bin/env bash
#Tessdf
while IFS=: read -r username password user_id group_id gecos home_dir shell; do
    # Display the formatted information
    echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd

